networks:
  backend:
  frontend:

services:
  mongo:
    image: mongo
    container_name: mongo-data
    restart: always
    networks:
      - backend
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=AzureDiamond
      - MONGO_INITDB_ROOT_PASSWORD=hunter2
  
  webapi:
    image: ${DOCKER_REGISTRY-}protected-api
    container_name: web-api
    networks:
      - backend
      - frontend
    build:
      context: ./ProtectedWebApi
      dockerfile: Dockerfile
    ports:
      - 5142:80
    depends_on:
      - mongo
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - MONGODB_CONN=mongodb://AzureDiamond:hunter2@mongo:27017
  
  client:
    image: ${DOCKER_REGISTRY-}protected-client
    container_name: blazor-client
    networks:
      - frontend
    depends_on:
      - webapi
    build:
      context: ./ProtectedBlazorWasm
      dockerfile: Dockerfile
    ports:
      - 5239:80